services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: modelo-login-api-app
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:9000
    networks:
      - modelo-login-api-laravel

  nginx:
    image: nginx:stable
    container_name: modelo-login-api-nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - modelo-login-api-laravel

  postgres:
    image: postgres
    container_name: modelo-login-api-postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - modelo-login-api-laravel

networks:
  modelo-login-api-laravel:
    driver: bridge

volumes:
  pgdata:
